### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by Thicool** [orzitsu/Inspider#1]
Hey there,

thanks for the contribution but i get the followeing error running python 3.5:
_______________________________________________________________________________________________
C:\Users\Jankl\Anaconda2\envs\Python3.5\python.exe C:/Users/Jankl/PycharmProjects/Inspider-master/Example.py
Successfully Logged in
Traceback (most recent call last):
  File "C:/Users/Jankl/PycharmProjects/Inspider-master/Example.py", line 20, in <module>
    follower_list = example.follower(username='instagram')
  File "C:\Users\Jankl\PycharmProjects\Inspider-master\Inspider.py", line 342, in follower
    data = self.read_user_init(username=username)
  File "C:\Users\Jankl\PycharmProjects\Inspider-master\Inspider.py", line 108, in read_user_init
    data = self.analyze_html(html=html)
  File "C:\Users\Jankl\PycharmProjects\Inspider-master\Inspider.py", line 90, in analyze_html
    data = json.loads(entry_data)
  File "C:\Users\Jankl\Anaconda2\envs\Python3.5\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Jankl\Anaconda2\envs\Python3.5\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Jankl\Anaconda2\envs\Python3.5\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 9 (char 9)
____________________________________________________________________________________________________________

Any idea? I am not a python pro but would really like to use this scraper for my research!
Thanks in advance

**Comment by orzitsu** [comment]
Instagram has updated it's API so I need some time to fix it.

**Comment by orzitsu** [comment]
Fixed.
